### ISSUE TITLE
[Feat] Make Readme!

### ISSUE THREAD

**Issue by ValseLee** [ValseLee/CLToaster#11]
### 📝 작업 목적
| ⚒️ Title | `Make Readme` | 
| :--- | :--- |
| 📜 **Description** | Readme를 멋들어지게 만들어봅시다 |

---

### 🛠️ Tasks

* [ ] 타겟 버전, Swift 버전, 라이브러리 이름, 아이콘
* [ ] 예시와 사용 용도
* [ ] carthage, spm, cocoapod
