### ISSUE TITLE
[Doc] 각주 작업 및 self QA

### ISSUE THREAD

**Issue by ValseLee** [ValseLee/CLToaster#17]
### 📝 작업 목적
| ⚒️ Title | `각주 작업 및 self QA` | 
| :--- | :--- |
| 📜 **Description** | 각주를 작성하고 self QA를 수행합니다. |

---

### 🛠️ Tasks

* [ ] public method, protocol에 대한 각주 작성
* [ ] DocC
* [ ] self QA
  * [ ] case 별 작동 여부 확인
  * [ ] 메모리 누수 확인
